#!/bin/bash
# Yet to be implemented
PROJECT_NAME={{project}}
PROJECT_PATH={{project_path}}
VENV_PATH={{project_venv}}


setup:
	${VENV_PATH}/bin/pip install pip --upgrade
	${VENV_PATH}/bin/pip install -e . --upgrade
	${VENV_PATH}/bin/pip install -e '.[testing]' --upgrade
	npm install
	npm install --only=dev

runtests:
	${VENV_PATH}/bin/python -m pytest -q

revision:
	@read -p "What did you add? " MSG && \
	cd ${PROJECT_PATH} &&\
	${VENV_PATH}/bin/alembic revision --autogenerate -m "$$MSG"

upgrade:
	cd ${PROJECT_PATH} && ${VENV_PATH}/bin/alembic upgrade head

downgrade:
	cd ${PROJECT_PATH} && ${VENV_PATH}/bin/alembic downgrade -1

run:
	cd ${PROJECT_PATH} && gulp watch &
	cd ${PROJECT_PATH} &&  ${VENV_PATH}/bin/pserve development.ini

watch:
	cd ${PROJECT_PATH} && npm watch
